/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        charcoal: "#0F172A",
        navy: "#0F172A",
        orange: "#FF6A00",
        orangeLight: "#FF7A1A",
        cream: "#FFFBF7",
        warmWhite: "#FFFBF7",
        softGray: "#F5F7FA",
        slateGray: "#64748B",
        dark: "#07111F",
        // Semantic theme colors mapping to CSS variables
        "theme-bg": "var(--bg-page)",
        "theme-bg-secondary": "var(--bg-surface-secondary)",
        "theme-surface": "var(--bg-surface)",
        "theme-surface-secondary": "var(--bg-surface-secondary)",
        "theme-surface-elevated": "var(--bg-surface-elevated)",
        "theme-card": "var(--bg-card)",
        "theme-card-elevated": "var(--bg-card-elevated)",
        "theme-overlay": "var(--bg-overlay)",
        "theme-text-primary": "var(--text-primary)",
        "theme-text-secondary": "var(--text-secondary)",
        "theme-text-muted": "var(--text-muted)",
        "theme-text-subtle": "var(--text-subtle)",
        "theme-border": "var(--border-main)",
        "theme-border-subtle": "var(--border-subtle)",
        "theme-border-card": "var(--border-card)",
        "theme-input-bg": "var(--input-bg)",
        "theme-input-border": "var(--input-border)",
        "theme-input-text": "var(--input-text)",
        "theme-input-placeholder": "var(--input-placeholder)",
        "theme-primary": "var(--primary)",
        "theme-primary-hover": "var(--primary-hover)",
        "theme-primary-light": "var(--primary-light)",
        "theme-navbar-bg": "var(--navbar-bg)",
        "theme-footer-bg": "var(--footer-bg)",
      },
      boxShadow: {
        "theme-sm": "var(--shadow-sm)",
        "theme-card": "var(--shadow-card)",
        "theme-elevated": "var(--shadow-elevated)",
      },
      fontFamily: {
        heading: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        body: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
      },
    },
  },
  plugins: [],
}
